# Generated by Django 3.0.3 on 2020-04-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='name',
        ),
    ]
